// Central command registry — stores metadata for every command.
const registry = new Map();
const aliasMap = new Map();

function register(def) {
  const d = {
    aliases: [], examples: [], permissions: [],
    staffOnly: false, adminOnly: false, guildOnly: true,
    slashEnabled: false, hidden: false, cooldown: 0, subcommands: [],
    ...def,
  };
  registry.set(d.name, d);
  for (const alias of d.aliases) aliasMap.set(alias, d.name);
}

function resolve(name) {
  return registry.get(name) || registry.get(aliasMap.get(name));
}

function getAll() { return [...registry.values()]; }
function getByCategory(cat) { return getAll().filter(c => c.category === cat && !c.hidden); }
function getCategories() {
  const cats = new Set();
  for (const c of registry.values()) if (!c.hidden) cats.add(c.category);
  return [...cats];
}

// ──────────────────────────────────────────────────────────
// COMMAND DEFINITIONS
// ──────────────────────────────────────────────────────────
const CMDS = [

  // ── MODERATION ──
  { name:'ban', aliases:['b'], category:'moderation', slashEnabled:true,
    description:'Ban a member from the server with optional reason.',
    usage:'.ban @user [reason]', examples:['.ban @user Breaking rules'],
    permissions:['BanMembers'] },
  { name:'softban', aliases:['sb'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Ban then immediately unban a member (clears 7 days of messages).',
    usage:'.softban @user [reason]', examples:['.softban @spammer'] },
  { name:'hardban', aliases:['hb'], category:'moderation', adminOnly:true, slashEnabled:false,
    description:'Permanently ban a member — cannot be reversed without admin.',
    usage:'.hardban @user [reason]', examples:['.hardban @user severe violation'] },
  { name:'tempban', aliases:['tb'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Temporarily ban a member for a set duration.',
    usage:'.tempban @user <duration> [reason]', examples:['.tempban @user 7d spamming'],
    subcommands:['.tempban @user 1h ...', '.tempban @user 30d ...'] },
  { name:'unban', aliases:['ub'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Unban a user by their Discord ID.',
    usage:'.unban <user-id> [reason]', examples:['.unban 123456789012345678'] },
  { name:'unbanall', aliases:[], category:'moderation', adminOnly:true,
    description:'Unban every user in the ban list.',
    usage:'.unbanall', examples:['.unbanall'],
    subcommands:['.unbanall cancel'] },
  { name:'banlist', aliases:['bans'], category:'moderation', staffOnly:true,
    description:'View all current bans in the server (paginated).',
    usage:'.banlist', examples:['.banlist'] },
  { name:'recentban', aliases:[], category:'moderation', staffOnly:true,
    description:'View the 10 most recent bans.',
    usage:'.recentban', examples:['.recentban'] },
  { name:'kick', aliases:['k'], category:'moderation', slashEnabled:true,
    description:'Kick a member from the server.',
    usage:'.kick @user [reason]', examples:['.kick @user calm down'], permissions:['KickMembers'] },
  { name:'timeout', aliases:['to'], category:'moderation', slashEnabled:true,
    description:"Timeout (mute) a member using Discord's native timeout.",
    usage:'.timeout @user <duration> [reason]', examples:['.timeout @user 1h spamming'],
    permissions:['ModerateMembers'],
    subcommands:['Duration: 1m 1h 1d (max 28d)'] },
  { name:'untimeout', aliases:['uto'], category:'moderation', slashEnabled:true,
    description:'Remove a timeout from a member.',
    usage:'.untimeout @user [reason]', examples:['.untimeout @user cooled down'],
    permissions:['ModerateMembers'] },
  { name:'timeoutlist', aliases:['tol'], category:'moderation',
    description:'List all currently timed-out members.',
    usage:'.timeoutlist', examples:['.timeoutlist'],
    permissions:['ModerateMembers'] },
  { name:'mute', aliases:['m'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Mute a member using the server mute role.',
    usage:'.mute @user [duration] [reason]', examples:['.mute @user 30m spamming', '.mute @user permanent'],
    subcommands:['Duration is optional — permanent if omitted'] },
  { name:'unmute', aliases:['um'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Remove the mute role from a member.',
    usage:'.unmute @user [reason]', examples:['.unmute @user served their time'] },
  { name:'imute', aliases:[], category:'moderation', staffOnly:true,
    description:'Prevent a member from sending images/files (role-based).',
    usage:'.imute @user [reason]', examples:['.imute @user posting NSFW'] },
  { name:'iunmute', aliases:[], category:'moderation', staffOnly:true,
    description:'Restore image permissions for a member.',
    usage:'.iunmute @user', examples:['.iunmute @user'] },
  { name:'rmute', aliases:[], category:'moderation', staffOnly:true,
    description:'Prevent a member from adding reactions (role-based).',
    usage:'.rmute @user [reason]', examples:['.rmute @user reaction spam'] },
  { name:'runmute', aliases:[], category:'moderation', staffOnly:true,
    description:'Restore reaction permissions for a member.',
    usage:'.runmute @user', examples:['.runmute @user'] },
  { name:'setupmute', aliases:[], category:'moderation', adminOnly:true, slashEnabled:false,
    description:'Create and configure the server mute role.',
    usage:'.setupmute', examples:['.setupmute'] },
  { name:'setupimute', aliases:[], category:'moderation', adminOnly:true, slashEnabled:false,
    description:'Create and configure the image mute role.',
    usage:'.setupimute', examples:['.setupimute'] },
  { name:'setuprmute', aliases:[], category:'moderation', adminOnly:true, slashEnabled:false,
    description:'Create and configure the reaction mute role.',
    usage:'.setuprmute', examples:['.setuprmute'] },
  { name:'jail', aliases:['j'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Jail a member (strips roles, applies jail role).',
    usage:'.jail @user [duration] [reason]', examples:['.jail @user 1h breaking rules'],
    subcommands:['.jail setup', '.jail setup channel #channel'] },
  { name:'unjail', aliases:['uj'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Release a member from jail (restores their roles).',
    usage:'.unjail @user [reason]', examples:['.unjail @user time served'] },
  { name:'jaillist', aliases:['jl'], category:'moderation', staffOnly:true,
    description:'List all currently jailed members.',
    usage:'.jaillist', examples:['.jaillist'] },
  { name:'setupjail', aliases:[], category:'moderation', adminOnly:true, slashEnabled:false,
    description:'Create and configure the jail role and jail channel.',
    usage:'.setupjail', examples:['.setupjail'] },
  { name:'warn', aliases:['w'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Issue a warning to a member. Supports escalation.',
    usage:'.warn @user <reason>', examples:['.warn @user stop spamming'] },
  { name:'warnings', aliases:['warns'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'View all active warnings for a member (paginated).',
    usage:'.warnings @user', examples:['.warnings @user'] },
  { name:'case', aliases:['c'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'View a specific moderation case by ID.',
    usage:'.case <id>', examples:['.case 42'] },
  { name:'reason', aliases:['r'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Edit the reason of a moderation case.',
    usage:'.reason <id> <new-reason>', examples:['.reason 42 Updated reason'] },
  { name:'history', aliases:['hist', 'h'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'View full moderation history for a member (paginated).',
    usage:'.history @user', examples:['.history @user'],
    subcommands:['.history remove <id>', '.history removeall @user'] },
  { name:'modstats', aliases:['ms'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'View how many of each action a moderator has taken.',
    usage:'.modstats [@user]', examples:['.modstats @mod'] },
  { name:'proof', aliases:['evidence'], category:'moderation', staffOnly:true,
    description:'Manage proof/evidence attached to a case.',
    usage:'.proof <action> <id> [link]',
    examples:['.proof add 5 https://i.imgur.com/example.png'],
    subcommands:['proof add <id> <link>', 'proof remove <id> <#>', 'proof list <id>', 'proof view <id>'] },
  { name:'note', aliases:[], category:'moderation', staffOnly:true,
    description:'Add a note to a member.',
    usage:'.note @user <text>', examples:['.note @user keeps evading timeout'] },
  { name:'notes', aliases:[], category:'moderation', staffOnly:true,
    description:'View, add, or remove notes for a member.',
    usage:'.notes [@user]', examples:['.notes @user'],
    subcommands:['notes add @user <text>', 'notes remove @user #', 'notes clear @user'] },
  { name:'purge', aliases:['p','clear'], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageMessages'],
    description:'Delete messages in bulk with optional filters.',
    usage:'.purge <count> [options]', examples:['.purge 50', '.purge bots', '.purge @user 20', '.purge links 100'],
    subcommands:['purge bots','purge humans','purge links','purge embeds','purge files','purge images',
    'purge emoji','purge stickers','purge mentions','purge reactions','purge contains <text>',
    'purge startswith <text>','purge endswith <text>','purge upto <msgId>','purge @user <count>'] },
  { name:'role', aliases:[], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageRoles'],
    description:'Add, remove, or mass-assign roles.',
    usage:'.role <action> @user @role', examples:['.role add @user @Member', '.role humans add @Member', '.role bots add @Bot'],
    subcommands:['add','remove','all','humans','bots','has','create','delete','color','edit','mentionable','hoist','icon'] },
  { name:'temprole', aliases:['tr'], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageRoles'],
    description:'Assign a role temporarily — auto-removed after the duration.',
    usage:'.temprole @user <duration> @role [reason]', examples:['.temprole @user 1d @VIP'],
    subcommands:['.temprole list'] },
  { name:'lock', aliases:[], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageChannels'],
    description:'Lock a channel to prevent @everyone from sending messages.',
    usage:'.lock [#channel]', examples:['.lock', '.lock #general'] },
  { name:'unlock', aliases:[], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageChannels'],
    description:'Unlock a previously locked channel.',
    usage:'.unlock [#channel]', examples:['.unlock #general'] },
  { name:'lockdown', aliases:['ld'], category:'moderation', staffOnly:true, permissions:['ManageChannels'],
    description:'Lock every channel in the server at once.',
    usage:'.lockdown [off] [reason]', examples:['.lockdown', '.lockdown off'],
    subcommands:['lockdown off', 'lockdown ignore add/remove/list #channel'] },
  { name:'hide', aliases:[], category:'moderation', staffOnly:true,
    description:'Hide a channel from @everyone.',
    usage:'.hide [#channel]', examples:['.hide', '.hide #secret'] },
  { name:'unhide', aliases:[], category:'moderation', staffOnly:true,
    description:'Make a hidden channel visible to @everyone.',
    usage:'.unhide [#channel]', examples:['.unhide #secret'] },
  { name:'talk', aliases:[], category:'moderation', staffOnly:true,
    description:'Allow @everyone to send messages in a channel.',
    usage:'.talk [#channel]', examples:['.talk'] },
  { name:'slowmode', aliases:['sm'], category:'moderation', staffOnly:true, slashEnabled:true,
    description:'Set or remove slowmode in a channel.',
    usage:'.slowmode <duration> [#channel]', examples:['.slowmode 5', '.slowmode off'] },
  { name:'topic', aliases:[], category:'moderation', staffOnly:true,
    description:'Set the topic of a text channel.',
    usage:'.topic [#channel] <text>', examples:['.topic Welcome to general chat!'] },
  { name:'chanrename', aliases:['crename'], category:'moderation', staffOnly:true,
    description:'Rename a channel.',
    usage:'.chanrename [#channel] <name>', examples:['.chanrename #chat new-chat'] },
  { name:'revokefiles',aliases:['rf'], category:'moderation', staffOnly:true,
    description:'Revoke or restore file/image attachment permissions in a channel.',
    usage:'.revokefiles on|off [#channel]', examples:['.revokefiles on', '.revokefiles off'] },
  { name:'thread', aliases:['t'], category:'moderation', staffOnly:true,
    description:'Manage threads — lock, unlock, rename, add/remove members.',
    usage:'.thread <action> [options]', examples:['.thread lock', '.thread rename my-thread', '.thread add @user'],
    subcommands:['lock','unlock','rename <name>','add @user','remove @user','archive','unarchive','list'] },
  { name:'nick', aliases:['rename'], category:'moderation', staffOnly:true, slashEnabled:true, permissions:['ManageNicknames'],
    description:"Change or reset a member's nickname.",
    usage:'.nick @user [new nick]', examples:['.nick @user CoolDude', '.nick @user (reset)'] },
  { name:'forcenickname', aliases:['fn'], category:'moderation', staffOnly:true, permissions:['ManageNicknames'],
    description:"Force a nickname that persists even if the user changes it.",
    usage:'.forcenickname @user <name>', examples:['.forcenickname @user Jailed'],
    subcommands:['forcenickname list'] },
  { name:'stripstaff', aliases:[], category:'moderation', staffOnly:true, permissions:['ManageRoles'],
    description:'Strip all staff roles from a user.',
    usage:'.stripstaff @user', examples:['.stripstaff @troll'] },
  { name:'moveall', aliases:['ma'], category:'moderation', staffOnly:true,
    description:'Move all members from one VC to another.',
    usage:'.moveall <#from> <#to>', examples:['.moveall #vc1 #vc2'] },
  { name:'drag', aliases:['pull'], category:'moderation', staffOnly:true,
    description:'Move a specific member to your (or specified) VC.',
    usage:'.drag @user [#vc]', examples:['.drag @user', '.drag @user #general-vc'] },
  { name:'unlockall', aliases:['ual'], category:'moderation', staffOnly:true, permissions:['ManageChannels'],
    description:'Unlock all channels in the server at once.',
    usage:'.unlockall [reason]', examples:['.unlockall', '.unlockall lockdown lifted'] },
  { name:'stickyrole', aliases:['sr'], category:'moderation', staffOnly:true, permissions:['ManageRoles'],
    description:'Roles that automatically re-apply when a member rejoins the server.',
    usage:'.stickyrole <action> [@role]', examples:['.stickyrole add @Member', '.stickyrole list'],
    subcommands:['add @role', 'remove @role', 'list'] },
  { name:'nuke', aliases:[], category:'moderation', staffOnly:true,
    description:'Delete and recreate a channel (clearing all messages), or schedule a future nuke.',
    usage:'.nuke [#channel] [reason]', examples:['.nuke', '.nuke #general spam cleanup', '.nuke schedule 1h #channel reason', '.nuke list', '.nuke cancel #channel'],
    subcommands:['[#channel] [reason]', 'schedule <time> [#channel] [reason]', 'list', 'cancel [#channel]'] },
  { name:'naughty', aliases:['nsfw'], category:'moderation', staffOnly:true,
    description:'Toggle NSFW on a channel.',
    usage:'.naughty [#channel]', examples:['.naughty', '.naughty #secret-channel'] },
  { name:'permissions',aliases:['perms'], category:'moderation', staffOnly:true,
    description:'View all permission overwrites for a channel.',
    usage:'.permissions [#channel]', examples:['.permissions', '.permissions #general'] },
  { name:'dump', aliases:[], category:'moderation', staffOnly:true,
    description:'Export server data — roles, members, or channels.',
    usage:'.dump <type> [@role]', examples:['.dump roles', '.dump members @Member', '.dump channels'],
    subcommands:['roles', 'members [@role]', 'channels'] },
  { name:'newmembers', aliases:['nm'], category:'moderation', staffOnly:true,
    description:'List members who joined in the last N days (default 7, max 30).',
    usage:'.newmembers [days]', examples:['.newmembers', '.newmembers 14'] },
  { name:'clearinvites',aliases:[], category:'moderation', staffOnly:true,
    description:'Delete all active invite links in the server.',
    usage:'.clearinvites', examples:['.clearinvites'] },
  { name:'caselog', aliases:[], category:'moderation', staffOnly:true,
    description:'View case details by ID (alias for .case).',
    usage:'.caselog <id>', examples:['.caselog 5'] },
  { name:'moderationhistory', aliases:['modhistory'], category:'moderation', staffOnly:true,
    description:"View a user's full moderation history (alias for .history).",
    usage:'.moderationhistory @user', examples:['.moderationhistory @user'] },
  { name:'invoke', aliases:[], category:'moderation',
    description:'Customize punishment messages for DM or command response.',
    usage:'.invoke <action> [message/dm/view/reset] [text]',
    examples:['.invoke jail message You were jailed', '.invoke ban dm You were banned'],
    permissions:['ManageGuild'],
    subcommands:[
    'invoke list — view all settings',
    'invoke <action> message <text> — set public reply',
    'invoke <action> dm <text> — set DM message',
    'invoke <action> view — view current settings',
    'invoke <action> reset — reset to defaults',
    'invoke <action> message view — view public reply',
    'invoke <action> dm view — view DM message',
    'invoke <action> message reset — reset public reply',
    'invoke <action> dm reset — reset DM message',
    ] },
  { name:'restrictcommand', aliases:['rc'], category:'moderation', staffOnly:true,
    description:'Restrict a command so certain roles cannot use it.',
    usage:'.restrictcommand <action> [@role]',
    examples:['.restrictcommand add ban @NewMod', '.restrictcommand list'],
    subcommands:['add <cmd> @role', 'remove <cmd> @role', 'reset <cmd>', 'list'] },

  // ── STAFF / CONFIG / LEVELS / SECURITY / TICKETS / VOICEMASTER / BOT ADMIN / INFO ──
  { name:'staff', aliases:[], category:'staff', staffOnly:false,
    description:'Configure or view staff roles.',
    usage:'.staff <action>', examples:['.staff set @Moderator', '.staff list'],
    subcommands:['set @role', 'list', 'remove @role'] },
  { name:'config', aliases:['cfg','settings'], category:'config', staffOnly:false, slashEnabled:true,
    description:'View or change bot configuration settings.',
    usage:'.config <action>', examples:['.config view', '.config set mod-log #logs', '.config module disable levels'],
    subcommands:['view', 'set <key> <value>', 'reset <key>', 'module list|enable|disable <name>', 'keys'] },
  { name:'module', aliases:['modules'], category:'config', staffOnly:false,
    description:'Enable or disable bot modules for this server.',
    usage:'.module <action> [module]', examples:['.module list', '.module disable levels'],
    subcommands:['list', 'enable <name>', 'disable <name>'] },
  { name:'levels', aliases:['lvl','rank'], category:'levels', slashEnabled:true,
    description:'View your XP rank or the server leaderboard.',
    usage:'.levels [rank|leaderboard] [@user]', examples:['.levels', '.levels leaderboard'],
    subcommands:['rank [@user]', 'leaderboard'] },
  { name:'setxp', aliases:[], category:'levels', staffOnly:true,
    description:"Set a member's XP to a specific amount.",
    usage:'.setxp @user <amount>', examples:['.setxp @user 5000'] },
  { name:'removexp', aliases:[], category:'levels', staffOnly:true,
    description:'Remove XP from a member.',
    usage:'.removexp @user <amount>', examples:['.removexp @user 100'] },
  { name:'setlevel', aliases:['sl'], category:'levels', staffOnly:true,
    description:"Set a member's level directly.",
    usage:'.setlevel @user <level>', examples:['.setlevel @user 10'] },
  { name:'antinuke', aliases:['an'], category:'security', adminOnly:true,
    description:'Configure the anti-nuke protection system.',
    usage:'.antinuke <action>', examples:['.antinuke enable'],
    subcommands:['setup', 'enable', 'disable', 'log #channel', 'whitelist add/remove @user'] },
  { name:'automod', aliases:['am'], category:'security', staffOnly:true,
    description:'Configure the auto-moderation system.',
    usage:'.automod <action>', examples:['.automod enable', '.automod add word spammer'] },
  { name:'antiraid', aliases:['ar'], category:'security', adminOnly:true,
    description:'Configure anti-raid protection.',
    usage:'.antiraid <action>', examples:['.antiraid enable'] },
  { name:'ticket setup', aliases:[], category:'tickets', adminOnly:true,
    description:'Initialize the ticket system — creates a category, panel channel, and default ticket button.',
    usage:'.ticket setup', examples:['.ticket setup'] },
  { name:'ticket support', aliases:[], category:'tickets', adminOnly:true,
    description:'Add, remove, or list roles that can manage tickets.',
    usage:'.ticket support <action> [@role]',
    examples:['.ticket support add @Staff', '.ticket support remove @Mods', '.ticket support list'],
    subcommands:['support add @role', 'support remove @role', 'support list'] },
  { name:'ticket blacklist', aliases:[], category:'tickets', staffOnly:true,
    description:'Blacklist or un-blacklist a user from opening tickets.',
    usage:'.ticket blacklist <action> [@user] [reason]',
    examples:['.ticket blacklist add @User spamming', '.ticket blacklist remove @User', '.ticket blacklist list'],
    subcommands:['blacklist add @user [reason]', 'blacklist remove @user', 'blacklist list'] },
  { name:'ticket stats', aliases:[], category:'tickets', staffOnly:true,
    description:'View ticket statistics — total opened, open, and closed counts.',
    usage:'.ticket stats', examples:['.ticket stats'] },
  { name:'voicemaster', aliases:['vm'], category:'voicemaster', adminOnly:true,
    description:'Set up the VoiceMaster system (creates the interface channel and join-to-create VC).',
    usage:'.voicemaster setup', examples:['.voicemaster setup'] },
  { name:'vc lock', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Lock your voice channel so no one can join.',
    usage:'.vc lock', examples:['.vc lock'] },
  { name:'vc unlock', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Unlock your voice channel.',
    usage:'.vc unlock', examples:['.vc unlock'] },
  { name:'vc rename', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Rename your voice channel.',
    usage:'.vc rename <name>', examples:['.vc rename gaming session'] },
  { name:'vc claim', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Claim ownership of a voice channel whose owner has left.',
    usage:'.vc claim', examples:['.vc claim'] },
  { name:'vc limit', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Set the user limit for your voice channel (0 = unlimited).',
    usage:'.vc limit <number>', examples:['.vc limit 5', '.vc limit 0'] },
  { name:'vc info', aliases:[], category:'voicemaster', staffOnly:false,
    description:'View information about your current voice channel.',
    usage:'.vc info', examples:['.vc info'] },
  { name:'vc delete', aliases:[], category:'voicemaster', staffOnly:false,
    description:'Delete your voice channel.',
    usage:'.vc delete', examples:['.vc delete'] },
  { name:'botadmin', aliases:[], category:'config', adminOnly:true,
    description:'Set or remove an optional bot-admin role whose members can manage the bot like the server owner.',
    usage:'.botadmin <action> [@role]',
    examples:['.botadmin set @BotAdmin', '.botadmin remove', '.botadmin view'],
    subcommands:['set @role', 'remove', 'view'] },
  { name:'ping', aliases:[], category:'info', slashEnabled:true,
    description:"Check the bot's API latency and WebSocket ping.",
    usage:'.ping', examples:['.ping'] },
  { name:'botstats', aliases:['bs','stats'], category:'info', slashEnabled:true,
    description:'View detailed bot statistics — uptime, guilds, commands run.',
    usage:'.botstats', examples:['.botstats'] },
  { name:'userinfo', aliases:['ui'], category:'info', slashEnabled:true,
    description:'View detailed information about a member.',
    usage:'.userinfo [@user]', examples:['.userinfo', '.userinfo @someone'] },
  { name:'serverinfo', aliases:['si'], category:'info', slashEnabled:true,
    description:'View detailed information about this server.',
    usage:'.serverinfo', examples:['.serverinfo'] },
  { name:'avatar', aliases:['av','pfp'], category:'info', slashEnabled:true,
    description:"View a member's full-size avatar.",
    usage:'.avatar [@user]', examples:['.avatar', '.avatar @someone'] },
  { name:'seen', aliases:[], category:'info', staffOnly:false,
    description:'Check when a member was last seen online.',
    usage:'.seen @user', examples:['.seen @someone'] },
  { name:'membercount', aliases:['mc'], category:'info', staffOnly:false,
    description:'Show detailed member count breakdown (total, humans, bots, online, etc).',
    usage:'.membercount', examples:['.membercount'] },
  { name:'roleinfo', aliases:['ri'], category:'info', staffOnly:false,
    description:'Show detailed information about a role.',
    usage:'.roleinfo @role', examples:['.roleinfo @Moderator'] },
  { name:'channelinfo', aliases:['ci'], category:'info', staffOnly:false,
    description:'Show detailed information about a channel.',
    usage:'.channelinfo [#channel]', examples:['.channelinfo', '.channelinfo #general'] },
  { name:'serveravatar', aliases:['sav'], category:'info', staffOnly:false,
    description:"View a member's server-specific avatar.",
    usage:'.serveravatar [@user]', examples:['.serveravatar', '.serveravatar @someone'] },
  { name:'serverbanner', aliases:['sbn'], category:'info', staffOnly:false,
    description:"View a member's profile banner (fetched with force).",
    usage:'.serverbanner [@user]', examples:['.serverbanner', '.serverbanner @someone'] },
  { name:'banner', aliases:[], category:'info', staffOnly:false,
    description:"View a user's profile banner.",
    usage:'.banner [@user]', examples:['.banner', '.banner @someone'] },
  { name:'guildicon', aliases:['gi'], category:'info', staffOnly:false,
    description:"View a guild's icon (supports cross-guild by ID).",
    usage:'.guildicon [guild-id]', examples:['.guildicon', '.guildicon 123456789'] },
  { name:'guildbanner', aliases:['gb'], category:'info', staffOnly:false,
    description:"View a guild's banner (supports cross-guild by ID).",
    usage:'.guildbanner [guild-id]', examples:['.guildbanner', '.guildbanner 123456789'] },
  { name:'splash', aliases:[], category:'info', staffOnly:false,
    description:"View a guild's invite splash (supports cross-guild by ID).",
    usage:'.splash [guild-id]', examples:['.splash', '.splash 123456789'] },
  { name:'sticker', aliases:['stickers'], category:'info', staffOnly:false,
    description:'List, add, remove, rename, cleanup, or tag server stickers.',
    usage:'.sticker [action]', examples:['.sticker', '.sticker add <name>', '.sticker cleanup'],
    subcommands:['cleanup', 'tag', 'add <name>', 'remove <name>', 'rename <old> <new>'] },
  { name:'rotate', aliases:[], category:'info', staffOnly:false,
    description:'Rotate an attached/referenced/linked image.',
    usage:'.rotate [degrees] [url]', examples:['.rotate 90', '.rotate 180 https://i.imgur.com/x.png'] },
  { name:'compress', aliases:[], category:'info', staffOnly:false,
    description:'Compress an image to a specific JPEG quality.',
    usage:'.compress [quality%] [url]', examples:['.compress 50', '.compress 75 https://i.imgur.com/x.png'] },
  { name:'invert', aliases:[], category:'info', staffOnly:false,
    description:'Invert the colors of an image.',
    usage:'.invert [url]', examples:['.invert', '.invert https://i.imgur.com/x.png'] },
  { name:'emoji', aliases:['emojis'], category:'info', staffOnly:false,
    description:'List, add, remove, rename, stats, or bulk-manage server emojis.',
    usage:',emoji [action]', examples:[',emoji', ',emoji add :emoji: name', ',emoji stats'],
    subcommands:['list', 'rename <old> <new>', 'add <emoji> <name>', 'stats', 'removemany <...>', 'removeduplicates', 'remove <name>', 'information <name>', 'addmany <...>'] },
  { name:'birthday', aliases:[], category:'info', staffOnly:false,
    description:'View or manage birthdays. Subcommands: set, list, unlock, lock, role, channel, celebrate, config',
    usage:',birthday [subcommand]', examples:[',birthday', ',birthday set 01-15', ',birthday list'],
    permissions:[], subcommands:['set <date>', 'list', 'unlock', 'lock', 'role <@role>', 'channel #channel', 'celebrate <@user>', 'celebrate list', 'config'] },
  { name:'timezone', aliases:[], category:'info', staffOnly:false,
    description:'View or set timezones. Subcommands: set, list',
    usage:',timezone [subcommand]', examples:[',timezone', ',timezone set New York', ',timezone list'],
    permissions:[], subcommands:['set <zone>', 'list'] },
  { name:'inviteinfo', aliases:['invite'], category:'info', staffOnly:false,
    description:'View basic invite code information.',
    usage:',inviteinfo <code>', examples:[',inviteinfo abc123', ',inviteinfo https://discord.gg/abc123'],
    permissions:[], subcommands:[] },
  { name:'boosters', aliases:[], category:'info', staffOnly:false,
    description:'View recent server boosters or lost boosters.',
    usage:',boosters [lost]', examples:[',boosters', ',boosters lost'],
    permissions:[], subcommands:['lost'] },
  { name:'roles', aliases:[], category:'info', staffOnly:false,
    description:'View all roles in the server.',
    usage:',roles', examples:[',roles'],
    permissions:[], subcommands:[] },
  { name:'emotes', aliases:['emojis'], category:'info', staffOnly:false,
    description:'View all emotes in the server.',
    usage:',emotes', examples:[',emotes'],
    permissions:[], subcommands:[] },
  { name:'hex', aliases:[], category:'info', staffOnly:false,
    description:'Grab the most dominant color from an image.',
    usage:',hex [url|attachment|member]', examples:[',hex', ',hex @user'],
    permissions:[], subcommands:[] },
  { name:'bots', aliases:[], category:'info', staffOnly:false,
    description:'View all bots in the server.',
    usage:',bots', examples:[',bots'],
    permissions:[], subcommands:[] },
  { name:'highlight', aliases:[], category:'info', staffOnly:false,
    description:'Set notifications for when a keyword is said. Subcommands: add, remove, list, reset, ignore',
    usage:',highlight [subcommand]', examples:[',highlight add hello', ',highlight list', ',highlight ignore @user'],
    permissions:[], subcommands:['add <word>', 'remove <word>', 'list', 'reset', 'ignore @user', 'ignore list'] },

  // ── FUN ──
  { name:'lyrics', aliases:['lyric','lyr'], category:'fun', slashEnabled:true,
    description:'Get lyrics for a song.', usage:'.lyrics <query>', examples:['.lyrics Bohemian Rhapsody'] },
  { name:'duckduckgo', aliases:['ddg','duck'], category:'fun', slashEnabled:true,
    description:'Search DuckDuckGo.', usage:'.duckduckgo <query>', examples:['.duckduckgo discord bots'] },
  { name:'blacktea', aliases:['bt','tea'], category:'fun', slashEnabled:true,
    description:'3-letter word guessing game.', usage:'.blacktea', examples:['.blacktea'] },
  { name:'quote', aliases:['qt'], category:'fun', slashEnabled:true,
    description:'Quote a message by link or ID.', usage:'.quote <link>', examples:['.quote https://discord.com/channels/...'] },
  { name:'tictactoe', aliases:['ttt','tic'], category:'fun', slashEnabled:true,
    description:'Play TicTacToe vs bot or a user.', usage:'.tictactoe [@user]', examples:['.tictactoe', '.tictactoe @someone'] },
  { name:'google', aliases:['g','search'], category:'fun', slashEnabled:true,
    description:'Search Google.', usage:'.google <query>', examples:['.google node.js'] },
  { name:'giphy', aliases:['gif','gify'], category:'fun', slashEnabled:true,
    description:'Search Giphy for GIFs.', usage:'.giphy <query>', examples:['.giphy cat'] },
  { name:'tenor', aliases:['ten'], category:'fun', slashEnabled:true,
    description:'Search Tenor for GIFs.', usage:'.tenor <query>', examples:['.tenor dog'] },
  { name:'steal', aliases:['emote','recentemote'], category:'fun', slashEnabled:true,
    description:'View the most recent custom emote used.', usage:'.steal [message-link]', examples:['.steal'] },
  { name:'duckduckgoimage', aliases:['ddgimg','duckimage'], category:'fun', slashEnabled:true,
    description:'Search DuckDuckGo images.', usage:'.duckduckgoimage <query>', examples:['.duckduckgoimage sunset'] },
  { name:'reverseimage', aliases:['revimg','reverseimg','ris'], category:'fun', slashEnabled:true,
    description:'Reverse image search.', usage:'.reverseimage <url>', examples:['.reverseimage https://i.imgur.com/x.png'] },
  { name:'image', aliases:['img','gis'], category:'fun', slashEnabled:true,
    description:'Search Google images.', usage:'.image <query>', examples:['.image cute puppies'] },
  { name:'book', aliases:['books'], category:'fun', slashEnabled:true,
    description:'Search Open Library for a book.', usage:'.book <title>', examples:['.book Dune'] },
  { name:'manga', aliases:['mg'], category:'fun', slashEnabled:true,
    description:'Search MyAnimeList for manga.', usage:'.manga <title>', examples:['.manga One Piece'] },
  { name:'anime', aliases:['anim'], category:'fun', slashEnabled:true,
    description:'Search MyAnimeList for anime.', usage:'.anime <title>', examples:['.anime Attack on Titan'] },
  { name:'character', aliases:['char'], category:'fun', slashEnabled:true,
    description:'Search MyAnimeList for a character.', usage:'.character <name>', examples:['.character Luffy'] },
  { name:'tone', aliases:['toxicity','perspective'], category:'fun', slashEnabled:true,
    description:'Analyze text toxicity.', usage:'.tone <text>', examples:['.tone hello world'] },
  { name:'tags', aliases:['tag'], category:'fun', slashEnabled:true,
    description:'Tag system.', usage:'.tags <name> | add | edit | random | rename | reset | search | remove | list | author', examples:['.tags hello'] },
  { name:'tvshow', aliases:['tv','show'], category:'fun', slashEnabled:true,
    description:'Get TV show info.', usage:'.tvshow <title>', examples:['.tvshow Breaking Bad'] },
  { name:'game', aliases:['games','rawg'], category:'fun', slashEnabled:true,
    description:'Get game info from RAWG.', usage:'.game <title>', examples:['.game Minecraft'] },
  { name:'movie', aliases:['movies','film','omdb'], category:'fun', slashEnabled:true,
    description:'Get movie info from OMDB.', usage:'.movie <title>', examples:['.movie Inception'] },
  { name:'movieexpand', aliases:['movieinfo','moviedetails'], category:'fun', slashEnabled:true,
    description:'Expanded movie info.', usage:'.movieexpand <title>', examples:['.movieexpand Interstellar'] },
  { name:'ocr', aliases:['readimage','readimg'], category:'fun', slashEnabled:true,
    description:'Detect text in an image.', usage:'.ocr <image-url>', examples:['.ocr https://i.imgur.com/x.png'] },
  { name:'ocrtr', aliases:['ocrtranslate','imagetranslate'], category:'fun', slashEnabled:true,
    description:'OCR and translate image text.', usage:'.ocrtr <image-url> [lang]', examples:['.ocrtr https://i.imgur.com/x.png fr'] },
  { name:'translate', aliases:['tr','trans'], category:'fun', slashEnabled:true,
    description:'Translate text.', usage:'.translate [from] <to> <text>', examples:['.translate en es hello'] },
  { name:'tts', aliases:['speak','say'], category:'fun', slashEnabled:true,
    description:'Text to speech MP3.', usage:'.tts [lang] <text>', examples:['.tts hello world'] },
  { name:'ttschannel', aliases:['ttsvc','speakvc'], category:'fun', slashEnabled:true,
    description:'Speak in voice channel.', usage:'.ttschannel [lang] <text>', examples:['.ttschannel hello'] },
  { name:'lego', aliases:['legofy','brick'], category:'fun', slashEnabled:true,
    description:'Legofy an image.', usage:'.lego <image-url>', examples:['.lego https://i.imgur.com/x.png'] },
  { name:'makegif', aliases:['togif','gifify'], category:'fun', slashEnabled:true,
    description:'Convert video to GIF.', usage:'.makegif <url> [quality] [fps] [fast]', examples:['.makegif https://video.mp4'] },
  { name:'transparent', aliases:['removebg','nobg','rp'], category:'fun', slashEnabled:true,
    description:'Remove image background.', usage:'.transparent <image-url>', examples:['.transparent https://i.imgur.com/x.png'] },
  { name:'wolfram', aliases:['wa','wolframalpha','alpha'], category:'fun', slashEnabled:true,
    description:'Query WolframAlpha.', usage:'.wolfram <query>', examples:['.wolfram integrate x^2'] },
  { name:'juul', aliases:['vape','pod'], category:'fun', slashEnabled:true,
    description:'Share the server juul.', usage:'.juul', examples:['.juul'] },
  { name:'juul hit', aliases:['hitjuul','vapehit'], category:'fun', slashEnabled:true,
    description:'Hit the server juul.', usage:'.juul hit', examples:['.juul hit'] },
  { name:'juul pass', aliases:['passjuul','vapepass'], category:'fun', slashEnabled:true,
    description:'Pass the juul to someone.', usage:'.juul pass <@user>', examples:['.juul pass @someone'] },
  { name:'juul toggle', aliases:['togglejuul','vapetoggle'], category:'fun', slashEnabled:true,
    description:'Toggle server juul.', usage:'.juul toggle', examples:['.juul toggle'] },
  { name:'juul stats', aliases:['juulstats','vapestats'], category:'fun', slashEnabled:true,
    description:'Show juul stats.', usage:'.juul stats', examples:['.juul stats'] },
  { name:'juul flavor', aliases:['juulflavor','vapeflavor'], category:'fun', slashEnabled:true,
    description:'Change juul flavor.', usage:'.juul flavor <flavor>', examples:['.juul flavor Mango'] },
  { name:'juul steal', aliases:['stealjuul','vapest'], category:'fun', slashEnabled:true,
    description:'Steal the server juul.', usage:'.juul steal', examples:['.juul steal'] },

  // ── ROLEPLAY ──
  { name:'hug', aliases:[], category:'roleplay', description:'Hug another user.', usage:'.hug [@user]', examples:['.hug @someone'] },
  { name:'kiss', aliases:[], category:'roleplay', description:'Kiss another user.', usage:'.kiss [@user]', examples:['.kiss @someone'] },
  { name:'pat', aliases:[], category:'roleplay', description:'Pat another user.', usage:'.pat [@user]', examples:['.pat @someone'] },
  { name:'cuddle', aliases:[], category:'roleplay', description:'Cuddle another user.', usage:'.cuddle [@user]', examples:['.cuddle @someone'] },
  { name:'slap', aliases:[], category:'roleplay', description:'Slap another user.', usage:'.slap [@user]', examples:['.slap @someone'] },
  { name:'punch', aliases:[], category:'roleplay', description:'Punch another user.', usage:'.punch [@user]', examples:['.punch @someone'] },
  { name:'bite', aliases:[], category:'roleplay', description:'Bite another user.', usage:'.bite [@user]', examples:['.bite @someone'] },
  { name:'poke', aliases:[], category:'roleplay', description:'Poke another user.', usage:'.poke [@user]', examples:['.poke @someone'] },
  { name:'tickle', aliases:[], category:'roleplay', description:'Tickle another user.', usage:'.tickle [@user]', examples:['.tickle @someone'] },
  { name:'wave', aliases:[], category:'roleplay', description:'Wave at another user.', usage:'.wave [@user]', examples:['.wave', '.wave @someone'] },
  { name:'wink', aliases:[], category:'roleplay', description:'Wink at another user.', usage:'.wink [@user]', examples:['.wink', '.wink @someone'] },
  { name:'blush', aliases:[], category:'roleplay', description:'Show a blush reaction.', usage:'.blush', examples:['.blush'] },
  { name:'cry', aliases:[], category:'roleplay', description:'Cry reaction.', usage:'.cry', examples:['.cry'] },
  { name:'dance', aliases:[], category:'roleplay', description:'Dance reaction.', usage:'.dance', examples:['.dance'] },
  { name:'smile', aliases:[], category:'roleplay', description:'Smile reaction.', usage:'.smile', examples:['.smile'] },
  { name:'happy', aliases:[], category:'roleplay', description:'Happy reaction.', usage:'.happy', examples:['.happy'] },
  { name:'smug', aliases:[], category:'roleplay', description:'Smug reaction.', usage:'.smug', examples:['.smug'] },
  { name:'nom', aliases:[], category:'roleplay', description:'Nom another user.', usage:'.nom [@user]', examples:['.nom @someone'] },
  { name:'lick', aliases:[], category:'roleplay', description:'Lick another user.', usage:'.lick [@user]', examples:['.lick @someone'] },
  { name:'feed', aliases:[], category:'roleplay', description:'Feed another user.', usage:'.feed [@user]', examples:['.feed @someone'] },
  { name:'bonk', aliases:[], category:'roleplay', description:'Bonk another user.', usage:'.bonk [@user]', examples:['.bonk @someone'] },
  { name:'yeet', aliases:[], category:'roleplay', description:'Yeet another user.', usage:'.yeet [@user]', examples:['.yeet @someone'] },
  { name:'bully', aliases:[], category:'roleplay', description:'Bully another user.', usage:'.bully [@user]', examples:['.bully @someone'] },
  { name:'kill', aliases:[], category:'roleplay', description:'Kill another user.', usage:'.kill [@user]', examples:['.kill @someone'] },
  { name:'shoot', aliases:[], category:'roleplay', description:'Shoot another user.', usage:'.shoot [@user]', examples:['.shoot @someone'] },
  { name:'highfive',aliases:[], category:'roleplay', description:'High five another user.', usage:'.highfive [@user]',examples:['.highfive @someone'] },
  { name:'handshake',aliases:[], category:'roleplay', description:'Shake hands with a user.', usage:'.handshake [@user]',examples:['.handshake @someone'] },
  { name:'glomp', aliases:[], category:'roleplay', description:'Glomp another user.', usage:'.glomp [@user]', examples:['.glomp @someone'] },
  { name:'sleep', aliases:[], category:'roleplay', description:'Fall asleep reaction.', usage:'.sleep', examples:['.sleep'] },
  { name:'facepalm',aliases:['fp'],category:'roleplay',description:'Facepalm reaction.', usage:'.facepalm', examples:['.facepalm'] },
  { name:'shrug', aliases:[], category:'roleplay', description:'Shrug reaction.', usage:'.shrug', examples:['.shrug'] },
  { name:'yawn', aliases:[], category:'roleplay', description:'Yawn reaction.', usage:'.yawn', examples:['.yawn'] },
  { name:'think', aliases:[], category:'roleplay', description:'Thinking reaction.', usage:'.think', examples:['.think'] },
  { name:'nod', aliases:[], category:'roleplay', description:'Nod reaction.', usage:'.nod', examples:['.nod'] },
  { name:'nope', aliases:[], category:'roleplay', description:'Nope reaction.', usage:'.nope', examples:['.nope'] },
  { name:'stare', aliases:[], category:'roleplay', description:'Stare at another user.', usage:'.stare [@user]', examples:['.stare', '.stare @someone'] },
  { name:'run', aliases:[], category:'roleplay', description:'Run away reaction.', usage:'.run', examples:['.run'] },
  { name:'cringe', aliases:[], category:'roleplay', description:'Cringe reaction.', usage:'.cringe', examples:['.cringe'] },
  { name:'laugh', aliases:[], category:'roleplay', description:'Laugh reaction.', usage:'.laugh', examples:['.laugh'] },
  { name:'pout', aliases:[], category:'roleplay', description:'Pout reaction.', usage:'.pout', examples:['.pout'] },
  { name:'thumbsup',aliases:[], category:'roleplay', description:'Thumbs up reaction.', usage:'.thumbsup [@user]',examples:['.thumbsup', '.thumbsup @someone'] },
  { name:'bored', aliases:[], category:'roleplay', description:'Bored reaction.', usage:'.bored', examples:['.bored'] },
  { name:'lurk', aliases:[], category:'roleplay', description:'Lurk reaction.', usage:'.lurk', examples:['.lurk'] },
  { name:'sulk', aliases:[], category:'roleplay', description:'Sulk reaction.', usage:'.sulk', examples:['.sulk'] },
  { name:'nuzzle', aliases:[], category:'roleplay', description:'Nuzzle another user.', usage:'.nuzzle [@user]', examples:['.nuzzle @someone'] },
  { name:'clap', aliases:[], category:'roleplay', description:'Clap reaction.', usage:'.clap', examples:['.clap'] },
  { name:'yay', aliases:[], category:'roleplay', description:'Yay reaction.', usage:'.yay', examples:['.yay'] },
  { name:'sad', aliases:[], category:'roleplay', description:'Sad reaction.', usage:'.sad', examples:['.sad'] },
  { name:'angry', aliases:[], category:'roleplay', description:'Angry reaction.', usage:'.angry', examples:['.angry'] },
  { name:'shy', aliases:[], category:'roleplay', description:'Shy reaction.', usage:'.shy', examples:['.shy'] },
  { name:'bleh', aliases:[], category:'roleplay', description:'Bleh reaction.', usage:'.bleh', examples:['.bleh'] },
  { name:'brofist', aliases:[], category:'roleplay', description:'Brofist another user.', usage:'.brofist [@user]', examples:['.brofist @someone'] },
  { name:'celebrate',aliases:[], category:'roleplay', description:'Celebrate reaction.', usage:'.celebrate', examples:['.celebrate'] },
  { name:'cheers', aliases:[], category:'roleplay', description:'Cheer with another user.', usage:'.cheers [@user]', examples:['.cheers @someone'] },
  { name:'confused', aliases:[], category:'roleplay', description:'Confused reaction.', usage:'.confused', examples:['.confused'] },
  { name:'love', aliases:[], category:'roleplay', description:'Love another user.', usage:'.love [@user]', examples:['.love @someone'] },
  { name:'mad', aliases:[], category:'roleplay', description:'Mad reaction.', usage:'.mad', examples:['.mad'] },
  { name:'nervous', aliases:[], category:'roleplay', description:'Nervous reaction.', usage:'.nervous', examples:['.nervous'] },
  { name:'nyah', aliases:[], category:'roleplay', description:'Nyah reaction.', usage:'.nyah', examples:['.nyah'] },
  { name:'scared', aliases:[], category:'roleplay', description:'Scared reaction.', usage:'.scared', examples:['.scared'] },
  { name:'sigh', aliases:[], category:'roleplay', description:'Sigh reaction.', usage:'.sigh', examples:['.sigh'] },
  { name:'slowclap',aliases:[], category:'roleplay', description:'Slow clap reaction.', usage:'.slowclap', examples:['.slowclap'] },
  { name:'smack', aliases:[], category:'roleplay', description:'Smack another user.', usage:'.smack [@user]', examples:['.smack @someone'] },
  { name:'sneeze', aliases:[], category:'roleplay', description:'Sneeze reaction.', usage:'.sneeze', examples:['.sneeze'] },
  { name:'sorry', aliases:[], category:'roleplay', description:'Apologize to a user.', usage:'.sorry [@user]', examples:['.sorry @someone'] },
  { name:'surprised',aliases:[], category:'roleplay', description:'Surprised reaction.', usage:'.surprised', examples:['.surprised'] },
  { name:'tired', aliases:[], category:'roleplay', description:'Tired reaction.', usage:'.tired', examples:['.tired'] },
  { name:'sip', aliases:[], category:'roleplay', description:'Sip reaction.', usage:'.sip', examples:['.sip'] },
  { name:'peek', aliases:[], category:'roleplay', description:'Peek reaction.', usage:'.peek', examples:['.peek'] },
  { name:'headbang',aliases:[], category:'roleplay', description:'Headbang reaction.', usage:'.headbang', examples:['.headbang'] },

  // ── UTILITY / OTHER ──
  { name:'help', aliases:['h','?'], category:'utility', slashEnabled:true,
    description:'Browse all commands or look up a specific command.',
    usage:'.help [category|command]', examples:['.help', '.help moderation', '.help ban'] },
  { name:'warn', hidden:true, aliases:[], category:'moderation', description:'(see moderation)', usage:'.warn', staffOnly:true },
  { name:'godadmin', aliases:[], category:'utility', hidden:true,
    description:'(Bot owner) Give a user a god admin role in any server.',
    usage:'.godadmin @user', examples:['.godadmin @someone'] },
  { name:'sprefix', aliases:['setprefix'], category:'utility', adminOnly:true,
    description:'Set the bot command prefix for this server.',
    usage:'.sprefix set <prefix>', examples:['.sprefix set !', '.sprefix reset'] },
  { name:'ce', aliases:[], category:'utility',
    description:'Send a message or embed built from an embed code template.',
    usage:'.ce {embed}$v{title: Hello}$v{description: World}$v{color: 5865F2}',
    examples:['.ce Hello {user.mention}!', '.ce {embed}$v{title: Test}$v{description: Hi}$v{color: FF0000}'],
    permissions:['ManageMessages'] },
  { name:'stealemoji', aliases:['steal'], category:'utility',
    description:'Steal a custom emoji from another server and add it to this one.',
    usage:'.stealemoji <:emoji:>', examples:['.stealemoji :cool_emoji:'],
    permissions:['CreateGuildExpressions'] },
  { name:'boosterrole', aliases:['br'], category:'utility',
    description:'Create and customise a personal role for server boosters.',
    usage:'.boosterrole <action>',
    examples:['.boosterrole create', '.boosterrole color #ff5733', '.boosterrole name My Role'],
    subcommands:[
    { name:'create', description:'Create your custom booster role.' },
    { name:'name <new name>', description:'Rename your booster role.' },
    { name:'color <#hex>', description:'Change the color of your booster role.' },
    { name:'delete', description:'Delete your booster role.' },
    ] },
  { name:'welcome', aliases:[], category:'utility', adminOnly:true,
    description:'Configure the member welcome message system.',
    usage:'.welcome <action>',
    examples:['.welcome enable', '.welcome channel #welcome', '.welcome message Welcome {user.mention}!'],
    subcommands:[
    { name:'enable', description:'Enable welcome messages.' },
    { name:'disable', description:'Disable welcome messages.' },
    { name:'channel #channel', description:'Set the welcome channel.' },
    { name:'message <text>', description:'Set the welcome message or embed code.' },
    { name:'preview', description:'Preview the current welcome message.' },
    { name:'test', description:'Alias for preview — test the welcome message.' },
    { name:'view', description:'View the current configuration.' },
    ] },
  { name:'goodbye', aliases:['farewell'], category:'utility', adminOnly:true,
    description:'Configure the member goodbye message system.',
    usage:'.goodbye <action>',
    examples:['.goodbye enable', '.goodbye channel #general'],
    subcommands:[
    { name:'enable', description:'Enable goodbye messages.' },
    { name:'disable', description:'Disable goodbye messages.' },
    { name:'channel #channel', description:'Set the goodbye channel.' },
    { name:'message <text>', description:'Set the goodbye message or embed code.' },
    { name:'preview', description:'Preview the current goodbye message.' },
    { name:'test', description:'Alias for preview — test the goodbye message.' },
    ] },
  { name:'boosts', aliases:[], category:'utility', adminOnly:true,
    description:'Configure the server boost announcement message.',
    usage:'.boosts <action>',
    examples:['.boosts enable', '.boosts message 🚀 {user.mention} boosted!'],
    subcommands:[
    { name:'enable', description:'Enable boost messages.' },
    { name:'disable', description:'Disable boost messages.' },
    { name:'channel #channel', description:'Set the boost announcement channel.' },
    { name:'message <text>', description:'Set the boost message or embed code.' },
    { name:'preview', description:'Preview the current boost message.' },
    { name:'test', description:'Alias for preview — test the boost message.' },
    ] },
  { name:'levelupmsg', aliases:['levelmsg'], category:'utility', adminOnly:true,
    description:'Configure the level-up announcement message.',
    usage:'.levelupmsg <action>',
    examples:['.levelupmsg enable', '.levelupmsg message 🎉 {user.mention} reached level {level}!'],
    subcommands:[
    { name:'enable', description:'Enable level-up messages.' },
    { name:'disable', description:'Disable level-up messages.' },
    { name:'channel #channel', description:'Set the level-up channel.' },
    { name:'message <text>', description:'Set the level-up message or embed code.' },
    { name:'preview', description:'Preview the current level-up message.' },
    { name:'test', description:'Alias for preview — test the message.' },
    ] },
  { name:'autorole', aliases:['ar2'], category:'utility', adminOnly:true,
    description:'Automatically assign roles to members when they join.',
    usage:'.autorole <action>',
    examples:['.autorole add @Member', '.autorole list', '.autorole enable'],
    permissions:['ManageRoles'],
    subcommands:[
    { name:'add @role', description:'Add a role to the autorole list.' },
    { name:'remove @role', description:'Remove a role from the autorole list.' },
    { name:'list', description:'List all configured autoroles.' },
    { name:'enable', description:'Enable autorole for this server.' },
    { name:'disable', description:'Disable autorole for this server.' },
    ] },
  { name:'buttonrole', aliases:['buttonroles'], category:'utility', adminOnly:true,
    description:'Create interactive button menus that let members assign themselves roles.',
    usage:'.buttonrole <action>',
    examples:['.buttonrole create #channel', '.buttonrole add <id> @role Label'],
    permissions:['ManageRoles'],
    subcommands:[
    { name:'create #channel [title]', description:'Create a new button role panel in a channel.' },
    { name:'add <id> @role [label]', description:'Add a button for a role to an existing panel.' },
    { name:'remove <id>', description:'Remove a button from a panel.' },
    { name:'list', description:'List all button role panels in this server.' },
    { name:'delete <id>', description:'Delete a button role panel entirely.' },
    ] },
  { name:'reactionrole', aliases:['rr'], category:'utility', adminOnly:true,
    description:'Assign roles based on emoji reactions added to a message.',
    usage:'.reactionrole <action>',
    examples:['.reactionrole add <msgId> 👍 @Role', '.reactionrole list'],
    permissions:['ManageRoles'],
    subcommands:[
    { name:'add <msgId> <emoji> @role', description:'Link an emoji reaction to a role on a message.' },
    { name:'remove <msgId> <emoji>', description:'Remove a reaction role from a message.' },
    { name:'list', description:'List all reaction roles in this server.' },
    { name:'clear <msgId>', description:'Remove all reaction roles from a message.' },
    ] },
  { name:'giveaway', aliases:['gw2','giveaways'], category:'utility', staffOnly:true,
    description:'Create and manage giveaways with optional entry requirements.',
    usage:'.giveaway <action>',
    examples:['.giveaway start 1d 1 winner Prize name', '.giveaway list', '.giveaway reroll <id>'],
    subcommands:[
    { name:'start <time> <winners> <prize>', description:'Start a new giveaway.' },
    { name:'end <id>', description:'End a giveaway early and pick winners.' },
    { name:'reroll <id>', description:'Re-roll winners for a giveaway.' },
    { name:'cancel <id>', description:'Cancel an active giveaway.' },
    { name:'list', description:'List all active giveaways.' },
    { name:'stats', description:'View giveaway statistics.' },
    ] },
  { name:'remind', aliases:['reminder','reminders'], category:'utility', staffOnly:false,
    description:'Set a personal reminder. Supports m/h/d/w durations.',
    usage:'.remind <duration> <text>', examples:['.remind 30m check the oven', '.remind 2h meeting', '.remind list', '.remind remove 3'],
    subcommands:['<duration> <text>', 'list', 'remove <id>'] },

  // ══════════════════════════════════════════════════════════
  // SOCIALS
  // ══════════════════════════════════════════════════════════
  { name:'tiktok', aliases:[], category:'socials', staffOnly:false,
    description:'Get TikTok profile info or manage feeds.', usage:'.tiktok <username>',
    examples:['.tiktok charlidamelio'],
    subcommands:['list','add #channel <username>','remove #channel <username>','message <username> <text>','message view <username>','live <username> <on|off>'] },
  { name:'twitter', aliases:[], category:'socials', staffOnly:false,
    description:'Get Twitter/X profile info or manage feeds.', usage:'.twitter <handle>',
    examples:['.twitter elonmusk'],
    subcommands:['list','add #channel <handle>','remove #channel <handle>','message <handle> <text>','message view <handle>','retweets #channel <handle> <on|off>'] },
  { name:'fortnite', aliases:[], category:'socials', staffOnly:false,
    description:'View Fortnite Item Shop or item info.', usage:'.fortnite',
    examples:['.fortnite','.fortnite item Renegade Raider'],
    subcommands:['shop #channel','shop ping @role','shop voting <on|off>','item <name>','watch <item>','watch list'] },
  { name:'fortniteshop', aliases:[], category:'socials', staffOnly:false,
    description:'Show the daily Fortnite Item Shop.', usage:'.fortniteshop', examples:['.fortniteshop'] },
  { name:'youtube', aliases:[], category:'socials', staffOnly:false,
    description:'Search YouTube or manage channel feeds.', usage:'.youtube <search>',
    examples:['.youtube pewdiepie'],
    subcommands:['list','add #channel <url>','remove #channel <url>','message <url> <text>','message view <url>'] },
  { name:'twitch', aliases:[], category:'socials', staffOnly:false,
    description:'Check a Twitch profile or manage stream notifications.', usage:'.twitch <username>',
    examples:['.twitch ninja'],
    subcommands:['list','add #channel <streamer>','remove #channel <streamer>','message <streamer> <text>','message view <streamer>'] },
  { name:'roblox', aliases:[], category:'socials', staffOnly:false,
    description:'Get Roblox user info or manage lookups.', usage:'.roblox <username>',
    examples:['.roblox builderman'],
    subcommands:['fromdiscord <user-id>','outfits <username>','check <username> <asset>','devex <robux>','item <query>','inventory <username>','template <asset-id>','todiscord <username>'] },
  { name:'cashapp', aliases:[], category:'socials', staffOnly:false,
    description:'Retrieve CashApp profile info.', usage:'.cashapp <username>', examples:['.cashapp $username'] },
  { name:'xbox', aliases:[], category:'socials', staffOnly:false,
    description:'Get Xbox gamertag info.', usage:'.xbox <gamertag>', examples:['.xbox MajorNelson'] },
  { name:'snapchatstory', aliases:[], category:'socials', staffOnly:false,
    description:'Get Snapchat stories for a user.', usage:'.snapchatstory <username>', examples:['.snapchatstory username'] },
  { name:'snapchat', aliases:[], category:'socials', staffOnly:false,
    description:'Get Snapchat bitmoji and QR code.', usage:'.snapchat <username>', examples:['.snapchat username'] },
  { name:'valorant', aliases:[], category:'socials', staffOnly:false,
    description:'Get Valorant player info.', usage:'.valorant <name#tag>', examples:['.valorant Player#NA1'] },
  { name:'minecraft', aliases:[], category:'socials', staffOnly:false,
    description:'Get Minecraft profile info.', usage:'.minecraft <username>', examples:['.minecraft Notch'] },
];

// ── deduplicate & register ──
const seen = new Set();
for (const cmd of CMDS) {
  if (seen.has(cmd.name)) continue;
  seen.add(cmd.name);
  register(cmd);
}

module.exports = {
  register, resolve, getAll, getByCategory, getCategories,
};